language: ruby
rvm:
  - 2.4.1
cache: bundler
addons:
  postgresql: 9.6
before-script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database dontfile_test;' -U postgres
script:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rails test
